### ISSUE TITLE
Examples using hapi need to require('@hapi/hapi') in order to avoid a loader error

### ISSUE THREAD

**Issue by mbeckner** [BretFisher/docker-mastery-for-nodejs#11]
~/Developer/GitHub/docker-mastery-for-nodejs/assignment-dockerfile
Marks-MacBook-Pro[11:00:36] node app.js
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'hapi'

**Comment by BretFisher** [comment]
This should be fixed, can you check again?

**Comment by mbeckner** [comment]
Fixed. Thanks.
