### ISSUE TITLE
Please check this out. This folder does not exist.

### ISSUE THREAD

**Issue by felinto-dev** [BretFisher/docker-mastery-for-nodejs#25]
Please check this out. This folder does not exist.

https://github.com/BretFisher/docker-mastery-for-nodejs/blob/673d35d3c86c750330e763157ce67178bc2d13d7/assignment-sweet-compose/result/docker-compose.test.yml#L15

**Comment by BretFisher** [comment]
Is this a course question? If so please describe your issue in detail in the Udemy Q&A so the team can help, and other students can learn. Thanks!

**Comment by felinto-dev** [comment]
Hi,

It is not a problem related to Docker itself. It seems that when you went to create this repository, you may have made a small mistake.

The folder that the docker-compose references "vote" does not exist.

**Comment by BretFisher** [comment]
Ah, just ignore that file. It's part of the original source code of that app. In this assignment, you're only using the docker-compose.yml in the root of `assignment-sweet-compose` and when you're done it should look like the one in `answer` directory. I'll delete this unnecessary test yaml. Thanks!
